// Componente Server — métricas calculadas no servidor, cache de 1 hora.
// Nenhum dado pessoal é exposto. Só mostra métricas com dados suficientes.
import { calcularMetricasPublicas } from "@/lib/metricas-publicas";

export async function TraccaoSection({ locale }: { locale: string }) {
  const metricas = await calcularMetricasPublicas();

  // Se não houver nenhuma métrica com dados, não renderiza a secção
  if (metricas.length === 0) return null;

  const titulo = locale === "en"
    ? "THE PLATFORM IN MOTION"
    : "A PLATAFORMA EM MOVIMENTO";

  const subtitulo = locale === "en"
    ? "Results generated by real usage of LinkCommerce."
    : "Resultados gerados por utilização real da LinkCommerce.";

  return (
    <section
      className="py-28 px-6"
      style={{ borderTop: "1px solid rgba(255,255,255,0.05)" }}
    >
      <div className="max-w-6xl mx-auto">

        {/* Cabeçalho editorial */}
        <div className="mb-16">
          <p className="text-[11px] font-bold tracking-[0.2em] uppercase mb-4"
            style={{ color: "rgba(131,129,251,0.7)" }}>
            {titulo}
          </p>
          <h2 className="text-4xl sm:text-5xl font-extrabold text-white leading-tight max-w-xl">
            {subtitulo}
          </h2>
        </div>

        {/* Grid de métricas — adapta colunas ao número de métricas disponíveis */}
        <div
          className="grid gap-0"
          style={{
            gridTemplateColumns: `repeat(${Math.min(metricas.length, 4)}, 1fr)`,
            borderTop: "1px solid rgba(255,255,255,0.08)",
          }}
        >
          {metricas.map((m, i) => (
            <div
              key={m.label}
              className="py-10 pr-10"
              style={{
                borderRight: i < metricas.length - 1 ? "1px solid rgba(255,255,255,0.08)" : "none",
                paddingLeft: i === 0 ? "0" : "2.5rem",
              }}
            >
              {/* Valor principal */}
              <p
                className="text-5xl sm:text-6xl font-extrabold mb-3 leading-none"
                style={{
                  background: "linear-gradient(135deg,#153DEC,#8381FB)",
                  WebkitBackgroundClip: "text",
                  WebkitTextFillColor: "transparent",
                  backgroundClip: "text",
                }}
              >
                {m.valor}
              </p>

              {/* Label */}
              <p className="text-[11px] font-bold tracking-[0.15em] uppercase text-white mb-1">
                {m.label}
              </p>

              {/* Sublabel */}
              {m.sublabel && (
                <p className="text-xs text-white/30 leading-snug max-w-[140px]">
                  {m.sublabel}
                </p>
              )}
            </div>
          ))}
        </div>

        {/* Nota de rodapé — transparência sobre a metodologia */}
        <p className="mt-8 text-[10px] text-white/20 tracking-wide uppercase">
          {locale === "en"
            ? "Real data · Aggregated · No personal data · Updated hourly"
            : "Dados reais · Agregados · Sem dados pessoais · Actualizado de hora em hora"}
        </p>
      </div>
    </section>
  );
}
